PACKAGE_NAME="ucksmp"
PACKAGE_VERSION="0.1.0"
AUTOINSTALL="yes"
MAKE="make KDIR=/lib/modules/${kernelver}/build"
CLEAN="make KDIR=/lib/modules/${kernelver}/build clean"
BUILT_MODULE_NAME="uck"
DEST_MODULE_LOCATION="/extra"
